### ISSUE TITLE
Sidebar height issue

### ISSUE THREAD

**Issue by webspicer** [StartBootstrap/startbootstrap-simple-sidebar#35]
Hi,

Thanks for give wonderful layout for us. i just need one more favor that the sidebar height is not coming 100%(up to bottom) after change mobile mode view by using chrome developer Tool bar.

the sidebar height having 100% height in normal browser view. if we go for mobile mode(F12), the height is not coming up to bottom coming only 70 or 80% only.

please help me on this issue

**Comment by jonasbleyl** [comment]
Add `width: 100%` and `position: fixed` in the `#wrapper` as shown below to fix this.

```css
#wrapper {
    width: 100%;
    position: fixed;
    padding-left: 0;
    -webkit-transition: all 0.5s ease;
    -moz-transition: all 0.5s ease;
    -o-transition: all 0.5s ease;
    transition: all 0.5s ease;
}
```
