### ISSUE TITLE
Bug: Menu incorrectly toggled on and off when re-size the window.

### ISSUE THREAD

**Issue by sunshineo** [StartBootstrap/startbootstrap-simple-sidebar#5]
Go to page http://ironsummitmedia.github.io/startbootstrap-simple-sidebar/# on desktop with wide browser window.
Click the Toggle button and hide the side menu.
Resize the window to small window and the side menu suddenly show up.

Go to page http://ironsummitmedia.github.io/startbootstrap-simple-sidebar/# on desktop with narrow browser window.
Click the Toggle button and show the side menu.
Resize the window to large window and the side menu suddenly went hidden.

**Comment by sunshineo** [comment]
So I read the code. "toggled" means show on small screen but hide on big screen. So this is kind of by design.

**Comment by carltonf** [comment]
I come across the same issue and I only work around this by adding code into $(window).resize(), a bit messy. I'd say it's a design limit, and I didn't figure how to do it without fiddling with "resize".

**Comment by sunshineo** [comment]
Yes. I don't think there is a css only option.

**Comment by Lyr3x** [comment]
where do i need to place the  $(window).resize() ?

**Comment by sunshineo** [comment]
I'm curious too. I did not figure it out either.

**Comment by davidtmiller** [comment]
Typically users aren't going to be dramatically resizing the window like this, but adding window resize into the JS might be a solution. I'll look into this and potentially add it into the next build if it doesn't make the page too slow.

**Comment by HarelM** [comment]
I came across this issue as well, I don't think it's wise that toggle can mean two things in separate screen sizes - for example I want to you this sidebar for layers in my map application - I need the toggle to have the same meaning on any size of device - when toggled the layers are shown, otherwise they are not.
the following css solved my issue - which was included in my app.css after this library's css.
it basically changes the toggle meaning on large devices so that toggle means visible.

``` css
@media(min-width:768px) {
    #wrapper {
        padding-left: 0;
    }

    #wrapper.toggled {
        padding-left: 250px;
    }

    #sidebar-wrapper {
        width: 0;
    }

    #wrapper.toggled #sidebar-wrapper {
        width: 250px;
    }

    #page-content-wrapper {
        padding: 20px;
        position: relative;
    }

    #wrapper.toggled #page-content-wrapper {
        position: relative;
        margin-right: -250px;
    }
}
```
